# starship prompt configuration
# See: https://starship.rs/config/#prompt


add_newline = true
# Replace the ">" symbol in the prompt with "âœ"
[character]
success_symbol = "[âœ](bold blue)"

[hostname]
ssh_only = false
format = "[âŸª]($style)[$hostname]($style)[âŸ«]($style) in "
# trim_at = ".companyname.com"
disabled = false
style = "bold green"

[directory]
disabled = false
truncation_length = 4
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_symbol = "â€¦/"

[env_var]
variable = "SHELL"
default = "unknown shell"
disabled = true
style = "bold green"

# [memory_usage]
# disabled = false
# show_percentage = true
# show_swap = false
# threshold = -1
# symbol = "ï¡š "

[time]
disabled = false
# format = "ğŸ•™[ %T ]"
use_12hr = true
format = "[$time]($style) "
#utc_time_offset = "-5"
#time_range = "10:00:00-14:00:00"

[username]
disabled = false
# show_always = true

[docker]
symbol = "ïŒˆ "

[git_state]
disabled = false

[git_branch]
symbol = "ï˜ "

[golang]
symbol = "î˜§ "

[haskell]
symbol = "î˜Ÿ "

[hg_branch]
symbol = "ï˜ "
#disabled = false

[java]
symbol = "î‰– "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
# symbol = "î‰ "

[package]
# symbol = "ï£– "

[php]
symbol = "î˜ˆ "

[python]
symbol = "î˜† "

[ruby]
symbol = "îˆ¾ "

[rust]
# symbol = "ï€“ "

[custom]

[custom.tab]
# description = "The current tab in the tab terminal multiplexer"
# command = "tab --starship"
# when = "tab --starship"
# shell = ["sh"]
# format = "[$output]($style) "
# style = "bold blue"




